version: '3.8'

services:
  db:
    image: mysql:9.3.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: usuarios
    volumes:
      - db-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    healthcheck: 
      test: ['CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 --password="1234" --silent']
      interval: 3s
      retries: 5
      start_period: 30s

  backend:
    build: ./backend
    restart: always
    env_file:
      - ./backend/.env
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      backend:
        condition: service_started

  image-service:
    build: ./image-service
    restart: always
    depends_on:
      backend:
        condition: service_started
      frontend:
        condition: service_started
        
  send-email: 
    build: ./sendEmail
    env_file:
      - ./sendEmail/.env
    restart: always

  # nagios:
  #   image: jasonrivers/nagios:latest
  #   container_name: nagios
  #   environment:
  #     - NAGIOS_FQDN=nagios.local
  #   volumes:
  #     - ./nagios/etc:/opt/nagios/etc
  #     - ./nagios/custom-plugins:/opt/Custom-Nagios-Plugins
  #   depends_on:
  #     - backend
  #     - db
  #     - send-email

volumes:
  db-data:
