versionApi: apps/v1
kind: Deployment
matadata:
    nome: {{ .Release.Name }}-backend
    labels:
        app: {{ .Release.Name }}-backend
spec:
    replicas: {{ .Values.replicaCount }}
    selector:
        matchLabels:
            app: {{ .Release.Name }}-backend
    strategy:
        type: Recreate
    template:
        metadeta:
            labels:
                app: {{ .Release.Name }}-backend
        spec:
            containers:
              - name: {{ .Release.Name }}-backend
                image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
                imagePullPolicy: {{ .Values.image.imagePullPolicy }}
                ports:
                  - containerPort: 3001
                env:             
                  - name: DB_HOST
                    valueFrom:
                        configMapKeyRef:
                            name: {{ .Release.Name }}-backend-configmap
                            key: db_host
                  - name: DB_USER
                    valueFrom:
                        secretKeyRef:
                            name: {{ .Release.Name }}-db-secret
                            key: username
                  - name: DB_PASS
                    valueFrom:
                        secretKeyRef:
                            name: {{ .Release.Name }}-db-secret
                            key: password
                  - name: DB_NAME
                    valueFrom:
                        configMapKeyRef:
                            name: {{ .Release.Name }}-backend-configmap
                            key: db_name
                  - name: JWT_SECRET
                    valueFrom:
                        secretKeyRef:
                            name: {{ .Release.Name }}-backend-secret
                            key: jwt_secret
                resources:
                    requets:
                        memory: "1Gi"
                        cpu: "1"
                    limits:
                        memory: "2Gi"
                        cpu: "2"
