apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    run: {{ .Chart.Name }}
spec: 
  ports:
    - port: 3001
      targetPort: 3001
      protocol: TCP
  selector:
    app: {{ .Chart.Name }}