apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-backend
  labels:
    run: {{ .Release.Name }}-backend
spec: 
  ports:
  - port: 3001
    targetPort: 3001
    protocol: TCP
  selector:
    app: {{ .Values.global.backend.name }}