apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ .Release.Name }}-image-service
    labels:
        app: {{ .Release.Name }}-image-service
spec:
    replicas: {{ .Values.replicaCount }}
    selector:
        matchLabels:
            app: {{ .Release.Name }}-image-service
    strategy:
        type: Recreate
    template:
        metadata:
            labels:
                app: {{ .Release.Name }}-image-service
        spec:
            containers:
              - name: {{ .Release.Name }}-image-service
                image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
                imagePullPolicy: {{ .Values.image.imagePullPolicy }}
                ports:
                  - containerPort: 3007
                env:
                  - name: DB_HOST
                    valueFrom:
                        configMapKeyRef:
                            name: {{ .Release.Name }}-db-configmap
                            key: db_host
                  - name: DB_USER
                    valueFrom:
                        secretKeyRef:
                            name: {{ .Release.Name }}-db-secret
                            key: username
                  - name: DB_PASS
                    valueFrom:
                        secretKeyRef:
                            name: {{ .Release.Name }}-db-secret
                            key: password
                  - name: DB_NAME
                    valueFrom:
                        configMapKeyRef:
                            name: {{ .Release.Name }}-db-configmap
                            key: db_name
            resources:
                requests:
                    memory: "1Gi"
                    cpu: "1"
                limits:
                    memory: "2Gi"
                    cpu: "2"
            

                  