apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    run: {{ .Chart.Name }}
spec: 
  ports:
  - port: 3007
    targetPort: 3007
    protocol: TCP
  selector:
    app: {{ .Chart.Name }}