apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-image-service
  labels:
    run: {{ .Release.Name }}-image-service
spec: 
  ports:
  - port: 3007
    targetPort: 3007
    protocol: TCP
  selector:
    app: {{ .Release.Name }}-image-service