apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-secret
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/basic-auth
data:
  username: cm9vdA==
  password: cm9vdA==
  root_password: {{ "root" | b64enc }}
